#!/usr/bin/env python3
import json
from pathlib import Path
P=Path(__file__).parents[1]/'comfyui/workflows/01_character_forge.json'
N=[];L=[];i=0;j=0
def o(n,t):return {'name':n,'type':t,'links':[]}
def q(n,t):return {'name':n,'type':t,'link':None}
def a(t,title,x,y,w=None,ins=[],outs=[]):
 global i;i+=1;z={'id':i,'type':t,'title':title,'pos':[x,y],'size':[320,110],'flags':{},'order':i-1,'mode':0,'inputs':ins,'outputs':outs,'properties':{'Node name for S&R':t}};z.update({'widgets_values':w} if w is not None else {});N.append(z);return i
def l(s,so,d,di,t):
 global j;j+=1;L.append([j,s,so,d,di,t]);N[s-1]['outputs'][so]['links'].append(j);N[d-1]['inputs'][di]['link']=j
un=a('UNETLoader','Load Qwen Image 2512',-900,-120,['qwen_image_2512_fp8_e4m3fn.safetensors','default'],outs=[o('MODEL','MODEL')]);cl=a('CLIPLoader','Load Qwen 2.5 VL text encoder',-900,20,['qwen_2.5_vl_7b_fp8_scaled.safetensors','qwen_image'],outs=[o('CLIP','CLIP')]);va=a('VAELoader','Load Qwen Image VAE',-900,160,['qwen_image_vae.safetensors'],outs=[o('VAE','VAE')])
neg=a('CLIPTextEncode','Shared negative prompt',-520,-200,['cartoon, anime, painting, illustration, glamour photography, fashion editorial, plastic skin, waxy skin, bad anatomy, deformed hands, extra fingers, duplicate person, cross-eyed, unreadable text, logo, watermark, armor, superhero, military sci-fi, glossy spaceship set'],[q('clip','CLIP')],[o('CONDITIONING','CONDITIONING')]);l(cl,0,neg,0,'CLIP')
base='Amara Okonkwo, 39-year-old Black woman, warm brown skin, close natural coiled hair, oval face, defined cheekbones, tired intelligent dark-brown eyes, composed observant presence; practical ochre civic jacket over charcoal thermal layers with repaired cuffs and small abstract civic pin; ultra realistic documentary photography, natural untreated skin with visible pores, subtle facial asymmetry, realistic fabric texture, grounded practical lighting, maintained but aging Habitat Sol civic interior, no glamour, no armor, no readable text.'
shots=[('Front Portrait','front-facing chest-up reference portrait, shoulders square, neutral expression, both eyes unobstructed','front_portrait',1104,1472),('Three-Quarter','three-quarter torso portrait, shoulders slightly left and head toward camera, calm thoughtful expression','three_quarter',1104,1472),('Side Profile','clean full left side-profile head-and-shoulders reference, clear nose jawline and hairline silhouette','side_profile',1104,1472),('Full Body','full-body standing reference from head to boots, relaxed natural stance, hands visible, practical work trousers and boots','full_body',1152,1536),('Expression','chest-up reference portrait, gentle restrained smile, candid human warmth, not exaggerated','expression',1104,1472)]
for k,(title,shot,slug,w,h) in enumerate(shots):
 y=-360+k*300;p=a('CLIPTextEncode',title+' prompt',-500,y,[base+' '+shot],[q('clip','CLIP')],[o('CONDITIONING','CONDITIONING')]);l(cl,0,p,0,'CLIP');e=a('EmptyLatentImage',title+' latent',-80,y,[w,h,2],outs=[o('LATENT','LATENT')]);s=a('KSampler',title+' sampler',280,y,[11111111+k*11111111,'fixed',50,4.0,'euler','simple',1.0],[q('model','MODEL'),q('positive','CONDITIONING'),q('negative','CONDITIONING'),q('latent_image','LATENT')],[o('LATENT','LATENT')]);d=a('VAEDecode',title+' decode',640,y,[],[q('samples','LATENT'),q('vae','VAE')],[o('IMAGE','IMAGE')]);z=a('SaveImage',title+' save',900,y,[f'habitat-sol/characters/CHARACTER_NAME/{slug}'],[q('images','IMAGE')]);
 for X in [(un,0,s,0,'MODEL'),(p,0,s,1,'CONDITIONING'),(neg,0,s,2,'CONDITIONING'),(e,0,s,3,'LATENT'),(s,0,d,0,'LATENT'),(va,0,d,1,'VAE'),(d,0,z,0,'IMAGE')]:l(*X)
g=[{'title':'0 — Qwen Image model loaders','bounding':[-950,-250,420,480],'color':'#3f789e','font_size':24},{'title':'1 — Five canonical character-reference views','bounding':[-520,-420,1780,1700],'color':'#365e36','font_size':24}]
P.write_text(json.dumps({'last_node_id':i,'last_link_id':j,'nodes':N,'links':L,'groups':g,'config':{},'extra':{'ds':{'scale':.8,'offset':[1000,250]},'info':{'name':'Qwen Character Forge — Habitat Sol','description':'Generate front, three-quarter, side-profile, full-body and expression references. Edit each identity prompt before running.'}},'version':.4},indent=2)+'\n')
