#!/usr/bin/env python3
"""Queue one Qwen Habitat Sol character-reference view via ComfyUI's API."""
import argparse,json,time,urllib.request,urllib.error,uuid
P={'elena':{'name':'Elena Reyes, 41-year-old Latina or Afro-Latina doctor from Habitat Elysium, dark hair with visible silver streaks, precise intelligent gaze, controlled expression with subtle warmth, compact clinical whites layered with a dark thermal vest and Mars-red scarf, practical daily clinic wear, Elysium-influenced clean lines softened by Sol scarcity','place':'compact worn Mars clinic, old clean equipment and human touches, no glossy hospital futurism'},'amara':{'name':'Amara Okonkwo, 39-year-old Black woman, warm brown skin, close natural coiled hair, tired intelligent dark-brown eyes, composed observant presence, practical ochre civic jacket over charcoal thermal layers with repaired cuffs and small abstract civic pin','place':'maintained but aging Habitat Sol civic corridor'}}
V={'front':'front-facing chest-up reference portrait, shoulders square, neutral expression, both eyes clearly visible','three-quarter':'three-quarter torso reference portrait, shoulders slightly left and head toward camera, calm thoughtful expression','profile':'clean full left side-profile head-and-shoulders reference, clear nose jawline and hairline silhouette','full-body':'full-body standing reference from head to boots, relaxed natural stance, hands visible','expression':'chest-up reference portrait, gentle restrained smile, candid human warmth, not exaggerated'}
NEG='cartoon, anime, painting, illustration, glamour photography, fashion editorial, plastic skin, waxy skin, bad anatomy, deformed hands, extra fingers, duplicate person, cross-eyed, unreadable text, logo, watermark, armor, superhero, military sci-fi, glossy spaceship set'
def main():
 a=argparse.ArgumentParser();a.add_argument('character',choices=P);a.add_argument('--view',choices=V,default='front');a.add_argument('--host',default='http://172.17.0.1:8188');a.add_argument('--seed',type=int,default=11111111);a.add_argument('--steps',type=int,default=50);a.add_argument('--wait',action='store_true');x=a.parse_args();c=P[x.character];pos=f"{c['name']}; {V[x.view]}; {c['place']}; ultra realistic Habitat Sol documentary photography, natural untreated skin with visible pores, subtle facial asymmetry, realistic fabric texture, grounded practical light, maintained repaired civilian Mars habitat, no readable text."
 q={'1':{'class_type':'UNETLoader','inputs':{'unet_name':'qwen_image_2512_fp8_e4m3fn.safetensors','weight_dtype':'default'}},'2':{'class_type':'CLIPLoader','inputs':{'clip_name':'qwen_2.5_vl_7b_fp8_scaled.safetensors','type':'qwen_image'}},'3':{'class_type':'VAELoader','inputs':{'vae_name':'qwen_image_vae.safetensors'}},'4':{'class_type':'CLIPTextEncode','inputs':{'text':pos,'clip':['2',0]}},'5':{'class_type':'CLIPTextEncode','inputs':{'text':NEG,'clip':['2',0]}},'6':{'class_type':'EmptyLatentImage','inputs':{'width':1104,'height':1472,'batch_size':1}},'7':{'class_type':'KSampler','inputs':{'model':['1',0],'positive':['4',0],'negative':['5',0],'latent_image':['6',0],'seed':x.seed,'steps':x.steps,'cfg':4.0,'sampler_name':'euler','scheduler':'simple','denoise':1.0}},'8':{'class_type':'VAEDecode','inputs':{'samples':['7',0],'vae':['3',0]}},'9':{'class_type':'SaveImage','inputs':{'images':['8',0],'filename_prefix':f'habitat-sol/characters/{x.character}/references/{x.view}'}}}
 r=urllib.request.Request(x.host+'/prompt',data=json.dumps({'prompt':q,'client_id':str(uuid.uuid4())}).encode(),headers={'Content-Type':'application/json'})
 try:
  with urllib.request.urlopen(r,timeout=60) as z: out=json.load(z)
 except urllib.error.HTTPError as e: raise SystemExit(e.read().decode())
 print(json.dumps({'prompt_id':out['prompt_id'],'character':x.character,'view':x.view,'seed':x.seed,'prompt':pos},indent=2))
 if x.wait:
  while True:
   time.sleep(3)
   with urllib.request.urlopen(x.host+'/history/'+out['prompt_id']) as z:h=json.load(z)
   if out['prompt_id'] in h: print(json.dumps(h[out['prompt_id']],indent=2));break
if __name__=='__main__':main()
